### ISSUE TITLE
select gives wrong number of arguments

### ISSUE THREAD

**Issue by thenickcox** [camertron/scuttle-server#11]
query:

```sql
select 
articles.id, articles.title, max(revisions.wp10) as revision_score, revisions.user_id 
from articles 
join revisions 
on articles.id=revisions.article_id 
where revisions.wp10 > 40 
and articles.namespace in (2, 118)
group by articles.id;
```

scuttle:
```ruby
Article.select(
  Article.arel_table[:id], Article.arel_table[:title], Revision.arel_table[:wp10].maximum.as('revision_score'), Revision.arel_table[:user_id]
).where(
  Revision.arel_table[:wp10].gt(40).and(Article.arel_table[:namespace].in(2, 118))
).joins(
  Article.arel_table.join(Revision.arel_table).on(
    Article.arel_table[:id].eq(Revision.arel_table[:article_id])
  ).join_sources
).group(Article.arel_table[:id])
```

Rails 4.1.8:
```sh
ArgumentError: wrong number of arguments (4 for 0..1)
```

Is this an issue with the ActiveRecord version?

**Comment by camertron** [comment]
Hey @thenickcox, thanks for the bug report. Sounds like this is probably an issue with activerecord versions, as you suspected. Scuttle hasn't really been tested with AR v4. This isn't the first time a discrepancy between v3 and v4 has caused issues either. FYI I probably won't have time to work on this for a while.

**Comment by thenickcox** [comment]
Understandable, @camertron. Thanks. 

Would you be interested in pointing me toward making a PR, or do you just want to skip it for now?

**Comment by camertron** [comment]
I would love to see a PR for this. What's your level of comfort with Java?

The [core of Scuttle](https://github.com/camertron/scuttle-java) is written in Java because I couldn't find a good SQL parser in Ruby. You'll need to isolate the problem first, i.e. which function call is causing the `ArgumentError`. I have a hunch it's because of the `in` statement - maybe it only takes an array now? `in`s are handled by the `ValueExpressionVisitor` class [here](https://github.com/camertron/scuttle-java/blob/master/src/main/java/com/camertron/Scuttle/ValueExpressionVisitor.java#L205) and [here](https://github.com/camertron/scuttle-java/blob/master/src/main/java/com/camertron/Scuttle/ValueExpressionVisitor.java#L218). [Line 230](https://github.com/camertron/scuttle-java/blob/master/src/main/java/com/camertron/Scuttle/ValueExpressionVisitor.java#L230) is the line that does the actual formatting of the operand (puts commas between the values).

You may find that `in` isn't the culprit; if that's the case, let me know who the real culprit is and I can point you in the right direction.

Thanks for your willingness to help!

**Comment by thenickcox** [comment]
Sorry for the delay. Unfortunately, the best answer to the question "What's your level of comfort with Java" is, "Surely not high enough to implement this." About the only thing I can contribute is that `ActiveRecord::QueryMethods::WhereChain#select` now [takes either a block or a list of columns](https://github.com/rails/rails/blob/21e05a041f467e0c356ece400a1edbd23f3e23cd/activerecord/lib/active_record/relation/query_methods.rb#L249). But the code I posted earlier seemed to fit into the list case, so I'm thoroughly confused. Sorry I couldn't be more help!

**Comment by camertron** [comment]
No problem @thenickcox! I'll see if I can make some time to address this.

**Comment by camertron** [comment]
Hey @thenickcox this should be fixed now. Took today to address a bunch of Scuttle issues.

**Comment by thenickcox** [comment]
Awesome! Thanks so much.
