### ISSUE TITLE
Cannot visit Integer

### ISSUE THREAD

**Issue by hrdwdmrbl** [camertron/scuttle-server#28]
When I tried to import my project, this is the error I got. " Cannot visit Integer"

I don't know what it could mean. Perhaps it doesn't like my app/model/concerns folder 🤷‍♂️

**Comment by camertron** [comment]
Hey @hrdwdmrbl, I assume you were trying to use the model introspection feature? My guess is you're running into this issue because your codebase is written in a modern version of Ruby (i.e. > 2.0). Scuttle uses [jruby-parser](https://github.com/jruby/jruby-parser) to parse Ruby code, which unfortunately hasn't been updated in a long time. I filed [an issue](https://github.com/camertron/scuttle-server/issues/30) just now as a reminder.

**Comment by hrdwdmrbl** [comment]
I was trying to use the Configure Associations feature of scuttle.io

Yes, my codebase does use ruby 2.7. I might be able to make a change to my code to get it parseable. Do you know what the big features missing in 1.x were? I think there's the `:` symbol-hash syntax. I started using Ruby with version 2.3 I believe...

**Comment by camertron** [comment]
The new hash syntax was added in Ruby 1.9 if I recall correctly. The best way to find the syntax problem is to run jruby-parser on the models in your app. You should be able to install JRuby pretty easily using something like rvm, rbenv, asdf, etc. You'll need to `gem install jruby-parser`, then run a script like this one that parses all your model files:

```ruby
require 'jruby-parser'

Dir.glob('/path/to/myapp/app/models/*.rb").each do |model_file|
  JRubyParser.parse(File.read(model_file))
end
```

**Comment by hrdwdmrbl** [comment]
Well that took me way too long to get going with but I finally managed it. I believe that the problem is most likely ruby's keyword argument syntax. 😌

**Comment by camertron** [comment]
@hrdwdmrbl ah yeah that makes sense :)
