### ISSUE TITLE
Can't handle CASE or WITH statements

### ISSUE THREAD

**Issue by hrdwdmrbl** [camertron/scuttle-server#29]
I read that this project isn't support anymore but I thought it might also be a bit useful as a signpost for others to note that the project also doesn't support CASE or WITH statements

**Comment by camertron** [comment]
Hey @hrdwdmrbl, where did you hear that the project isn't supported anymore? While it's true I don't have a lot of time these days to work on it, I absolutely welcome and appreciate pull requests and even still make contributions from time to time. Thanks for filing this issue, it's great to maintain a list of missing features, etc.

**Comment by camertron** [comment]
Oh also, Scuttle should handle `CASE`/`WITH` statements. Can you provide some details around what query you're trying to parse?

**Comment by hrdwdmrbl** [comment]
Hi @camertron . I heard about the project from your conference talk back in 2014! 😁. 

I would give you a Pull Request but I think the work is mostly in Java, eh? What's where the parsing is done.

Here's a couple fragments of what didn't work. I simplified them from their original statement because the original statements were very large. If you could show me a simple CASE and WITH that work, maybe I could try to amend my statements so that they conform better to what is expected.

```
CASE
  WHEN (
    (TABLE_FOO.compare_at_price IS NOT NULL)
  AND
    (TABLE_FOO.compare_at_price > TABLE_FOO.price)
  ) THEN 1
  ELSE 0
END
```

```
WITH TABLE_FOO_t AS (
  SELECT
    "TABLE_FOO"."id",
    "TABLE_FOO"."title",
  FROM
    "TABLE_FOO"
  WHERE
    "TABLE_FOO"."user_id" = 17
)
SELECT
  t.*
FROM
  TABLE_FOO_t t
```

**Comment by camertron** [comment]
Yeah, the parser is written in Java because it uses ANTLR and, at the time, ANTLR didn't have a Ruby target. Even now, there's no official Ruby target for ANTLR, and the unofficial ones are quite immature and slow :( Hopefully someday the story will be different. I [tried my hand](http://github.com/camertron/antlr4-native-rb) at using the C++ target to create native extensions for Ruby, but, after much effort, I still occasionally see segfaults that I'm not smart enough to debug.

When I first added support for `CASE` statements in 2015, Arel didn't support them natively, so I had to wrap them in `Arel.sql`. Here's what Scuttle generates if I copy/paste your first statement in and surround it with a `SELECT`, i.e.:

```sql
SELECT CASE
  WHEN (
    (TABLE_FOO.compare_at_price IS NOT NULL)
  AND
    (TABLE_FOO.compare_at_price > TABLE_FOO.price)
  ) THEN 1
  ELSE 0
END FROM foo
```

```ruby
Foo.select(
  Arel.sql(
    'CASE
  WHEN (
      
    (TABLE_FOO.compare_at_price IS NOT NULL)
  AND
    (TABLE_FOO.compare_at_price > TABLE_FOO.price)
  
    ) THEN 1
  ELSE 0
END'
  )
)
```

I think the problem with the second statement is that the ANTLR grammar I'm using doesn't seem to support `WITH` statements. I found it in the Apache Tajo project, which unfortunately now [appears to be dead](https://whimsy.apache.org/board/minutes/Tajo.html#2020-09-16). I can try my hand at adding `WITH` support to the grammar, but in the meantime check out [this blog post](https://jakeyesbeck.com/2016/03/13/the-power-of-arel/) for how to do them in Arel.

Finally, I just added better `CASE` support to Scuttle. For your first statement, it now generates:

```ruby
Foo.select(
  Arel::Nodes::Case.new.when(
    Arel::Nodes::Group.new(
      TableFoo.arel_table[:compare_at_price].not_eq(nil).and(
        TableFoo.arel_table[:compare_at_price].gt(TableFoo.arel_table[:price])
      )
    )
  ).then(1).else(0)
)
```

**Comment by hrdwdmrbl** [comment]
Thank you for the explanation and link. I think my primary stumbling block when it comes to AREL is knowing how its AST is composed. I think what I need to do is read something like https://jpospisil.com/2014/06/16/the-definitive-guide-to-arel-the-sql-manager-for-ruby.html in order to understand how the nodes are allowed to fit together. I had hoped that I could kind of learn AREL by picking up patterns by shoving my giant query into Scuttle and seeing how it AREL-ized it :)

**Comment by camertron** [comment]
@hrdwdmrbl hahaha yeah. Well, my goal is to make that possible! It's just that 1) there aren't necessarily always 1:1 mappings between SQL and Arel, and 2) it's hard for Scuttle to cover every use-case, since the surface area of SQL is enormous.

**Comment by hrdwdmrbl** [comment]
Yeah, absolutely. I think if it's covering every Arel case, that's good enough.

**Comment by camertron** [comment]
Ah well sadly I think Scuttle probably only covers ~50% of everything Arel has to offer. However, I think that 50% covers maybe 85% of the use-cases out there. Or at least, I think it does because I don't hear from people too often anymore about missing features. I've sort of been relying on people submitting issues to know what the holes are.

**Comment by camertron** [comment]
I'm going to close this issue because I shipped updated `CASE`/`WHEN` support last weekend, but please feel free to keep the discussion going if desired :)
